/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Tue Feb  3 19:48:41 2026.
 */

#ifndef ROVER_H
#define ROVER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ROVER_GPS_POSITION_FRAME_ID (0x100u)
#define ROVER_GPS_VELOCITY_FRAME_ID (0x101u)
#define ROVER_GPS_ACCURACY_FRAME_ID (0x102u)
#define ROVER_IMU_ACCEL_FRAME_ID (0x103u)
#define ROVER_IMU_GYRO_FRAME_ID (0x104u)
#define ROVER_IMU_ORIENTATION_FRAME_ID (0x105u)
#define ROVER_IMU_QUATERNION_FRAME_ID (0x106u)

/* Frame lengths in bytes. */
#define ROVER_GPS_POSITION_LENGTH (8u)
#define ROVER_GPS_VELOCITY_LENGTH (8u)
#define ROVER_GPS_ACCURACY_LENGTH (8u)
#define ROVER_IMU_ACCEL_LENGTH (8u)
#define ROVER_IMU_GYRO_LENGTH (8u)
#define ROVER_IMU_ORIENTATION_LENGTH (8u)
#define ROVER_IMU_QUATERNION_LENGTH (8u)

/* Extended or standard frame types. */
#define ROVER_GPS_POSITION_IS_EXTENDED (0)
#define ROVER_GPS_VELOCITY_IS_EXTENDED (0)
#define ROVER_GPS_ACCURACY_IS_EXTENDED (0)
#define ROVER_IMU_ACCEL_IS_EXTENDED (0)
#define ROVER_IMU_GYRO_IS_EXTENDED (0)
#define ROVER_IMU_ORIENTATION_IS_EXTENDED (0)
#define ROVER_IMU_QUATERNION_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define ROVER_GPS_POSITION_CYCLE_TIME_MS (100u)
#define ROVER_GPS_VELOCITY_CYCLE_TIME_MS (100u)
#define ROVER_GPS_ACCURACY_CYCLE_TIME_MS (100u)
#define ROVER_IMU_ACCEL_CYCLE_TIME_MS (20u)
#define ROVER_IMU_GYRO_CYCLE_TIME_MS (20u)
#define ROVER_IMU_ORIENTATION_CYCLE_TIME_MS (50u)
#define ROVER_IMU_QUATERNION_CYCLE_TIME_MS (50u)

/* Signal choices. */


/* Frame Names. */
#define ROVER_GPS_POSITION_NAME "GPS_Position"
#define ROVER_GPS_VELOCITY_NAME "GPS_Velocity"
#define ROVER_GPS_ACCURACY_NAME "GPS_Accuracy"
#define ROVER_IMU_ACCEL_NAME "IMU_Accel"
#define ROVER_IMU_GYRO_NAME "IMU_Gyro"
#define ROVER_IMU_ORIENTATION_NAME "IMU_Orientation"
#define ROVER_IMU_QUATERNION_NAME "IMU_Quaternion"

/* Signal Names. */
#define ROVER_GPS_POSITION_GPS_LATITUDE_NAME "GPS_Latitude"
#define ROVER_GPS_POSITION_GPS_LONGITUDE_NAME "GPS_Longitude"
#define ROVER_GPS_VELOCITY_GPS_SPEED_NAME "GPS_Speed"
#define ROVER_GPS_VELOCITY_GPS_COURSE_NAME "GPS_Course"
#define ROVER_GPS_VELOCITY_GPS_FIX_TYPE_NAME "GPS_FixType"
#define ROVER_GPS_VELOCITY_GPS_NUM_SATS_NAME "GPS_NumSats"
#define ROVER_GPS_VELOCITY_GPS_HDOP_NAME "GPS_HDOP"
#define ROVER_GPS_ACCURACY_GPS_H_ACC_NAME "GPS_hAcc"
#define ROVER_GPS_ACCURACY_GPS_V_ACC_NAME "GPS_vAcc"
#define ROVER_IMU_ACCEL_IMU_ACCEL_X_NAME "IMU_AccelX"
#define ROVER_IMU_ACCEL_IMU_ACCEL_Y_NAME "IMU_AccelY"
#define ROVER_IMU_ACCEL_IMU_ACCEL_Z_NAME "IMU_AccelZ"
#define ROVER_IMU_ACCEL_IMU_CAL_ACCEL_NAME "IMU_CalAccel"
#define ROVER_IMU_GYRO_IMU_GYRO_X_NAME "IMU_GyroX"
#define ROVER_IMU_GYRO_IMU_GYRO_Y_NAME "IMU_GyroY"
#define ROVER_IMU_GYRO_IMU_GYRO_Z_NAME "IMU_GyroZ"
#define ROVER_IMU_GYRO_IMU_CAL_GYRO_NAME "IMU_CalGyro"
#define ROVER_IMU_ORIENTATION_IMU_HEADING_NAME "IMU_Heading"
#define ROVER_IMU_ORIENTATION_IMU_PITCH_NAME "IMU_Pitch"
#define ROVER_IMU_ORIENTATION_IMU_ROLL_NAME "IMU_Roll"
#define ROVER_IMU_ORIENTATION_IMU_CAL_SYS_NAME "IMU_CalSys"
#define ROVER_IMU_ORIENTATION_IMU_CAL_MAG_NAME "IMU_CalMag"
#define ROVER_IMU_QUATERNION_IMU_QUAT_W_NAME "IMU_QuatW"
#define ROVER_IMU_QUATERNION_IMU_QUAT_X_NAME "IMU_QuatX"
#define ROVER_IMU_QUATERNION_IMU_QUAT_Y_NAME "IMU_QuatY"
#define ROVER_IMU_QUATERNION_IMU_QUAT_Z_NAME "IMU_QuatZ"

/**
 * Signals in message GPS_Position.
 *
 * GPS Position with centimeter precision
 *
 * All signal values are as on the CAN bus.
 */
struct rover_gps_position_t {
    /**
     * Range: -900000000..900000000 (-90..90 deg)
     * Scale: 1e-07
     * Offset: 0
     */
    int32_t gps_latitude;

    /**
     * Range: -1800000000..1800000000 (-180..180 deg)
     * Scale: 1e-07
     * Offset: 0
     */
    int32_t gps_longitude;
};

/**
 * Signals in message GPS_Velocity.
 *
 * GPS Velocity and fix quality
 *
 * All signal values are as on the CAN bus.
 */
struct rover_gps_velocity_t {
    /**
     * Range: 0..16777000 (0..16777 m/s)
     * Scale: 0.001
     * Offset: 0
     */
    uint32_t gps_speed;

    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t gps_course;

    /**
     * Range: 0..5 (0..5 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t gps_fix_type;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t gps_num_sats;

    /**
     * Range: 0..255 (0..25.5 -)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t gps_hdop;
};

/**
 * Signals in message GPS_Accuracy.
 *
 * GPS Position accuracy estimates
 *
 * All signal values are as on the CAN bus.
 */
struct rover_gps_accuracy_t {
    /**
     * Range: 0..4294967000 (0..4294967 m)
     * Scale: 0.001
     * Offset: 0
     */
    uint32_t gps_h_acc;

    /**
     * Range: 0..4294967000 (0..4294967 m)
     * Scale: 0.001
     * Offset: 0
     */
    uint32_t gps_v_acc;
};

/**
 * Signals in message IMU_Accel.
 *
 * IMU linear acceleration + calibration status
 *
 * All signal values are as on the CAN bus.
 */
struct rover_imu_accel_t {
    /**
     * Range: -32000..32000 (-32..32 m/s2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t imu_accel_x;

    /**
     * Range: -32000..32000 (-32..32 m/s2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t imu_accel_y;

    /**
     * Range: -32000..32000 (-32..32 m/s2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t imu_accel_z;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t imu_cal_accel;
};

/**
 * Signals in message IMU_Gyro.
 *
 * IMU angular velocity + calibration status
 *
 * All signal values are as on the CAN bus.
 */
struct rover_imu_gyro_t {
    /**
     * Range: -32700..32700 (-327..327 deg/s)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t imu_gyro_x;

    /**
     * Range: -32700..32700 (-327..327 deg/s)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t imu_gyro_y;

    /**
     * Range: -32700..32700 (-327..327 deg/s)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t imu_gyro_z;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t imu_cal_gyro;
};

/**
 * Signals in message IMU_Orientation.
 *
 * IMU Euler orientation + calibration status
 *
 * All signal values are as on the CAN bus.
 */
struct rover_imu_orientation_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t imu_heading;

    /**
     * Range: -18000..18000 (-180..180 deg)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t imu_pitch;

    /**
     * Range: -18000..18000 (-180..180 deg)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t imu_roll;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t imu_cal_sys;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t imu_cal_mag;
};

/**
 * Signals in message IMU_Quaternion.
 *
 * IMU Quaternion orientation
 *
 * All signal values are as on the CAN bus.
 */
struct rover_imu_quaternion_t {
    /**
     * Range: -32000..32000 (-3.2..3.2 -)
     * Scale: 0.0001
     * Offset: 0
     */
    int16_t imu_quat_w;

    /**
     * Range: -32000..32000 (-3.2..3.2 -)
     * Scale: 0.0001
     * Offset: 0
     */
    int16_t imu_quat_x;

    /**
     * Range: -32000..32000 (-3.2..3.2 -)
     * Scale: 0.0001
     * Offset: 0
     */
    int16_t imu_quat_y;

    /**
     * Range: -32000..32000 (-3.2..3.2 -)
     * Scale: 0.0001
     * Offset: 0
     */
    int16_t imu_quat_z;
};

/**
 * Pack message GPS_Position.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_gps_position_pack(
    uint8_t *dst_p,
    const struct rover_gps_position_t *src_p,
    size_t size);

/**
 * Unpack message GPS_Position.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_gps_position_unpack(
    struct rover_gps_position_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from GPS_Position.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_gps_position_init(struct rover_gps_position_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t rover_gps_position_gps_latitude_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_gps_position_gps_latitude_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_gps_position_gps_latitude_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t rover_gps_position_gps_longitude_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_gps_position_gps_longitude_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_gps_position_gps_longitude_is_in_range(int32_t value);

/**
 * Pack message GPS_Velocity.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_gps_velocity_pack(
    uint8_t *dst_p,
    const struct rover_gps_velocity_t *src_p,
    size_t size);

/**
 * Unpack message GPS_Velocity.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_gps_velocity_unpack(
    struct rover_gps_velocity_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from GPS_Velocity.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_gps_velocity_init(struct rover_gps_velocity_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t rover_gps_velocity_gps_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_gps_velocity_gps_speed_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_gps_velocity_gps_speed_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t rover_gps_velocity_gps_course_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_gps_velocity_gps_course_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_gps_velocity_gps_course_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t rover_gps_velocity_gps_fix_type_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_gps_velocity_gps_fix_type_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_gps_velocity_gps_fix_type_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t rover_gps_velocity_gps_num_sats_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_gps_velocity_gps_num_sats_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_gps_velocity_gps_num_sats_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t rover_gps_velocity_gps_hdop_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_gps_velocity_gps_hdop_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_gps_velocity_gps_hdop_is_in_range(uint8_t value);

/**
 * Pack message GPS_Accuracy.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_gps_accuracy_pack(
    uint8_t *dst_p,
    const struct rover_gps_accuracy_t *src_p,
    size_t size);

/**
 * Unpack message GPS_Accuracy.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_gps_accuracy_unpack(
    struct rover_gps_accuracy_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from GPS_Accuracy.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_gps_accuracy_init(struct rover_gps_accuracy_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t rover_gps_accuracy_gps_h_acc_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_gps_accuracy_gps_h_acc_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_gps_accuracy_gps_h_acc_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t rover_gps_accuracy_gps_v_acc_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_gps_accuracy_gps_v_acc_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_gps_accuracy_gps_v_acc_is_in_range(uint32_t value);

/**
 * Pack message IMU_Accel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_imu_accel_pack(
    uint8_t *dst_p,
    const struct rover_imu_accel_t *src_p,
    size_t size);

/**
 * Unpack message IMU_Accel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_imu_accel_unpack(
    struct rover_imu_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from IMU_Accel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_imu_accel_init(struct rover_imu_accel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_accel_imu_accel_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_accel_imu_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_accel_imu_accel_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_accel_imu_accel_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_accel_imu_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_accel_imu_accel_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_accel_imu_accel_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_accel_imu_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_accel_imu_accel_z_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t rover_imu_accel_imu_cal_accel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_accel_imu_cal_accel_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_accel_imu_cal_accel_is_in_range(uint8_t value);

/**
 * Pack message IMU_Gyro.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_imu_gyro_pack(
    uint8_t *dst_p,
    const struct rover_imu_gyro_t *src_p,
    size_t size);

/**
 * Unpack message IMU_Gyro.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_imu_gyro_unpack(
    struct rover_imu_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from IMU_Gyro.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_imu_gyro_init(struct rover_imu_gyro_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_gyro_imu_gyro_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_gyro_imu_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_gyro_imu_gyro_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_gyro_imu_gyro_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_gyro_imu_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_gyro_imu_gyro_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_gyro_imu_gyro_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_gyro_imu_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_gyro_imu_gyro_z_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t rover_imu_gyro_imu_cal_gyro_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_gyro_imu_cal_gyro_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_gyro_imu_cal_gyro_is_in_range(uint8_t value);

/**
 * Pack message IMU_Orientation.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_imu_orientation_pack(
    uint8_t *dst_p,
    const struct rover_imu_orientation_t *src_p,
    size_t size);

/**
 * Unpack message IMU_Orientation.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_imu_orientation_unpack(
    struct rover_imu_orientation_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from IMU_Orientation.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_imu_orientation_init(struct rover_imu_orientation_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t rover_imu_orientation_imu_heading_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_orientation_imu_heading_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_orientation_imu_heading_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_orientation_imu_pitch_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_orientation_imu_pitch_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_orientation_imu_pitch_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_orientation_imu_roll_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_orientation_imu_roll_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_orientation_imu_roll_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t rover_imu_orientation_imu_cal_sys_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_orientation_imu_cal_sys_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_orientation_imu_cal_sys_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t rover_imu_orientation_imu_cal_mag_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_orientation_imu_cal_mag_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_orientation_imu_cal_mag_is_in_range(uint8_t value);

/**
 * Pack message IMU_Quaternion.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_imu_quaternion_pack(
    uint8_t *dst_p,
    const struct rover_imu_quaternion_t *src_p,
    size_t size);

/**
 * Unpack message IMU_Quaternion.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_imu_quaternion_unpack(
    struct rover_imu_quaternion_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from IMU_Quaternion.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_imu_quaternion_init(struct rover_imu_quaternion_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_quaternion_imu_quat_w_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_quaternion_imu_quat_w_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_quaternion_imu_quat_w_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_quaternion_imu_quat_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_quaternion_imu_quat_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_quaternion_imu_quat_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_quaternion_imu_quat_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_quaternion_imu_quat_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_quaternion_imu_quat_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_imu_quaternion_imu_quat_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_quaternion_imu_quat_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_quaternion_imu_quat_z_is_in_range(int16_t value);


#ifdef __cplusplus
}
#endif

#endif
