/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Tue Feb  3 19:48:41 2026.
 */

#include <string.h>

#include "rover.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int rover_gps_position_pack(
    uint8_t *dst_p,
    const struct rover_gps_position_t *src_p,
    size_t size)
{
    uint32_t gps_latitude;
    uint32_t gps_longitude;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    gps_latitude = (uint32_t)src_p->gps_latitude;
    dst_p[0] |= pack_left_shift_u32(gps_latitude, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(gps_latitude, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(gps_latitude, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(gps_latitude, 24u, 0xffu);
    gps_longitude = (uint32_t)src_p->gps_longitude;
    dst_p[4] |= pack_left_shift_u32(gps_longitude, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(gps_longitude, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(gps_longitude, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(gps_longitude, 24u, 0xffu);

    return (8);
}

int rover_gps_position_unpack(
    struct rover_gps_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t gps_latitude;
    uint32_t gps_longitude;

    if (size < 8u) {
        return (-EINVAL);
    }

    gps_latitude = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    gps_latitude |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    gps_latitude |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    gps_latitude |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->gps_latitude = (int32_t)gps_latitude;
    gps_longitude = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    gps_longitude |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    gps_longitude |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    gps_longitude |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->gps_longitude = (int32_t)gps_longitude;

    return (0);
}

int rover_gps_position_init(struct rover_gps_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_gps_position_t));

    return 0;
}

int32_t rover_gps_position_gps_latitude_encode(double value)
{
    return (int32_t)(value / 1e-07);
}

double rover_gps_position_gps_latitude_decode(int32_t value)
{
    return ((double)value * 1e-07);
}

bool rover_gps_position_gps_latitude_is_in_range(int32_t value)
{
    return ((value >= -900000000) && (value <= 900000000));
}

int32_t rover_gps_position_gps_longitude_encode(double value)
{
    return (int32_t)(value / 1e-07);
}

double rover_gps_position_gps_longitude_decode(int32_t value)
{
    return ((double)value * 1e-07);
}

bool rover_gps_position_gps_longitude_is_in_range(int32_t value)
{
    return ((value >= -1800000000) && (value <= 1800000000));
}

int rover_gps_velocity_pack(
    uint8_t *dst_p,
    const struct rover_gps_velocity_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->gps_speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->gps_speed, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->gps_speed, 16u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->gps_course, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->gps_course, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->gps_fix_type, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->gps_num_sats, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->gps_hdop, 0u, 0xffu);

    return (8);
}

int rover_gps_velocity_unpack(
    struct rover_gps_velocity_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->gps_speed = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->gps_speed |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->gps_speed |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->gps_course = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->gps_course |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->gps_fix_type = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->gps_num_sats = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->gps_hdop = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int rover_gps_velocity_init(struct rover_gps_velocity_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_gps_velocity_t));

    return 0;
}

uint32_t rover_gps_velocity_gps_speed_encode(double value)
{
    return (uint32_t)(value / 0.001);
}

double rover_gps_velocity_gps_speed_decode(uint32_t value)
{
    return ((double)value * 0.001);
}

bool rover_gps_velocity_gps_speed_is_in_range(uint32_t value)
{
    return (value <= 16777000u);
}

uint16_t rover_gps_velocity_gps_course_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double rover_gps_velocity_gps_course_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool rover_gps_velocity_gps_course_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

uint8_t rover_gps_velocity_gps_fix_type_encode(double value)
{
    return (uint8_t)(value);
}

double rover_gps_velocity_gps_fix_type_decode(uint8_t value)
{
    return ((double)value);
}

bool rover_gps_velocity_gps_fix_type_is_in_range(uint8_t value)
{
    return (value <= 5u);
}

uint8_t rover_gps_velocity_gps_num_sats_encode(double value)
{
    return (uint8_t)(value);
}

double rover_gps_velocity_gps_num_sats_decode(uint8_t value)
{
    return ((double)value);
}

bool rover_gps_velocity_gps_num_sats_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t rover_gps_velocity_gps_hdop_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double rover_gps_velocity_gps_hdop_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool rover_gps_velocity_gps_hdop_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int rover_gps_accuracy_pack(
    uint8_t *dst_p,
    const struct rover_gps_accuracy_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->gps_h_acc, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->gps_h_acc, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->gps_h_acc, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->gps_h_acc, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->gps_v_acc, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->gps_v_acc, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->gps_v_acc, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->gps_v_acc, 24u, 0xffu);

    return (8);
}

int rover_gps_accuracy_unpack(
    struct rover_gps_accuracy_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->gps_h_acc = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->gps_h_acc |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->gps_h_acc |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->gps_h_acc |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->gps_v_acc = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->gps_v_acc |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->gps_v_acc |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->gps_v_acc |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int rover_gps_accuracy_init(struct rover_gps_accuracy_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_gps_accuracy_t));

    return 0;
}

uint32_t rover_gps_accuracy_gps_h_acc_encode(double value)
{
    return (uint32_t)(value / 0.001);
}

double rover_gps_accuracy_gps_h_acc_decode(uint32_t value)
{
    return ((double)value * 0.001);
}

bool rover_gps_accuracy_gps_h_acc_is_in_range(uint32_t value)
{
    return (value <= 4294967000u);
}

uint32_t rover_gps_accuracy_gps_v_acc_encode(double value)
{
    return (uint32_t)(value / 0.001);
}

double rover_gps_accuracy_gps_v_acc_decode(uint32_t value)
{
    return ((double)value * 0.001);
}

bool rover_gps_accuracy_gps_v_acc_is_in_range(uint32_t value)
{
    return (value <= 4294967000u);
}

int rover_imu_accel_pack(
    uint8_t *dst_p,
    const struct rover_imu_accel_t *src_p,
    size_t size)
{
    uint16_t imu_accel_x;
    uint16_t imu_accel_y;
    uint16_t imu_accel_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    imu_accel_x = (uint16_t)src_p->imu_accel_x;
    dst_p[0] |= pack_left_shift_u16(imu_accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(imu_accel_x, 8u, 0xffu);
    imu_accel_y = (uint16_t)src_p->imu_accel_y;
    dst_p[2] |= pack_left_shift_u16(imu_accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(imu_accel_y, 8u, 0xffu);
    imu_accel_z = (uint16_t)src_p->imu_accel_z;
    dst_p[4] |= pack_left_shift_u16(imu_accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(imu_accel_z, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->imu_cal_accel, 0u, 0xffu);

    return (8);
}

int rover_imu_accel_unpack(
    struct rover_imu_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t imu_accel_x;
    uint16_t imu_accel_y;
    uint16_t imu_accel_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    imu_accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    imu_accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->imu_accel_x = (int16_t)imu_accel_x;
    imu_accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    imu_accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->imu_accel_y = (int16_t)imu_accel_y;
    imu_accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    imu_accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->imu_accel_z = (int16_t)imu_accel_z;
    dst_p->imu_cal_accel = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int rover_imu_accel_init(struct rover_imu_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_imu_accel_t));

    return 0;
}

int16_t rover_imu_accel_imu_accel_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double rover_imu_accel_imu_accel_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool rover_imu_accel_imu_accel_x_is_in_range(int16_t value)
{
    return ((value >= -32000) && (value <= 32000));
}

int16_t rover_imu_accel_imu_accel_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double rover_imu_accel_imu_accel_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool rover_imu_accel_imu_accel_y_is_in_range(int16_t value)
{
    return ((value >= -32000) && (value <= 32000));
}

int16_t rover_imu_accel_imu_accel_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double rover_imu_accel_imu_accel_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool rover_imu_accel_imu_accel_z_is_in_range(int16_t value)
{
    return ((value >= -32000) && (value <= 32000));
}

uint8_t rover_imu_accel_imu_cal_accel_encode(double value)
{
    return (uint8_t)(value);
}

double rover_imu_accel_imu_cal_accel_decode(uint8_t value)
{
    return ((double)value);
}

bool rover_imu_accel_imu_cal_accel_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int rover_imu_gyro_pack(
    uint8_t *dst_p,
    const struct rover_imu_gyro_t *src_p,
    size_t size)
{
    uint16_t imu_gyro_x;
    uint16_t imu_gyro_y;
    uint16_t imu_gyro_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    imu_gyro_x = (uint16_t)src_p->imu_gyro_x;
    dst_p[0] |= pack_left_shift_u16(imu_gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(imu_gyro_x, 8u, 0xffu);
    imu_gyro_y = (uint16_t)src_p->imu_gyro_y;
    dst_p[2] |= pack_left_shift_u16(imu_gyro_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(imu_gyro_y, 8u, 0xffu);
    imu_gyro_z = (uint16_t)src_p->imu_gyro_z;
    dst_p[4] |= pack_left_shift_u16(imu_gyro_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(imu_gyro_z, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->imu_cal_gyro, 0u, 0xffu);

    return (8);
}

int rover_imu_gyro_unpack(
    struct rover_imu_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t imu_gyro_x;
    uint16_t imu_gyro_y;
    uint16_t imu_gyro_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    imu_gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    imu_gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->imu_gyro_x = (int16_t)imu_gyro_x;
    imu_gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    imu_gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->imu_gyro_y = (int16_t)imu_gyro_y;
    imu_gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    imu_gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->imu_gyro_z = (int16_t)imu_gyro_z;
    dst_p->imu_cal_gyro = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int rover_imu_gyro_init(struct rover_imu_gyro_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_imu_gyro_t));

    return 0;
}

int16_t rover_imu_gyro_imu_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double rover_imu_gyro_imu_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool rover_imu_gyro_imu_gyro_x_is_in_range(int16_t value)
{
    return ((value >= -32700) && (value <= 32700));
}

int16_t rover_imu_gyro_imu_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double rover_imu_gyro_imu_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool rover_imu_gyro_imu_gyro_y_is_in_range(int16_t value)
{
    return ((value >= -32700) && (value <= 32700));
}

int16_t rover_imu_gyro_imu_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double rover_imu_gyro_imu_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool rover_imu_gyro_imu_gyro_z_is_in_range(int16_t value)
{
    return ((value >= -32700) && (value <= 32700));
}

uint8_t rover_imu_gyro_imu_cal_gyro_encode(double value)
{
    return (uint8_t)(value);
}

double rover_imu_gyro_imu_cal_gyro_decode(uint8_t value)
{
    return ((double)value);
}

bool rover_imu_gyro_imu_cal_gyro_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int rover_imu_orientation_pack(
    uint8_t *dst_p,
    const struct rover_imu_orientation_t *src_p,
    size_t size)
{
    uint16_t imu_pitch;
    uint16_t imu_roll;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->imu_heading, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->imu_heading, 8u, 0xffu);
    imu_pitch = (uint16_t)src_p->imu_pitch;
    dst_p[2] |= pack_left_shift_u16(imu_pitch, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(imu_pitch, 8u, 0xffu);
    imu_roll = (uint16_t)src_p->imu_roll;
    dst_p[4] |= pack_left_shift_u16(imu_roll, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(imu_roll, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->imu_cal_sys, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->imu_cal_mag, 0u, 0xffu);

    return (8);
}

int rover_imu_orientation_unpack(
    struct rover_imu_orientation_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t imu_pitch;
    uint16_t imu_roll;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->imu_heading = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->imu_heading |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    imu_pitch = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    imu_pitch |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->imu_pitch = (int16_t)imu_pitch;
    imu_roll = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    imu_roll |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->imu_roll = (int16_t)imu_roll;
    dst_p->imu_cal_sys = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->imu_cal_mag = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int rover_imu_orientation_init(struct rover_imu_orientation_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_imu_orientation_t));

    return 0;
}

uint16_t rover_imu_orientation_imu_heading_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double rover_imu_orientation_imu_heading_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool rover_imu_orientation_imu_heading_is_in_range(uint16_t value)
{
    return (value <= 36000u);
}

int16_t rover_imu_orientation_imu_pitch_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double rover_imu_orientation_imu_pitch_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool rover_imu_orientation_imu_pitch_is_in_range(int16_t value)
{
    return ((value >= -18000) && (value <= 18000));
}

int16_t rover_imu_orientation_imu_roll_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double rover_imu_orientation_imu_roll_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool rover_imu_orientation_imu_roll_is_in_range(int16_t value)
{
    return ((value >= -18000) && (value <= 18000));
}

uint8_t rover_imu_orientation_imu_cal_sys_encode(double value)
{
    return (uint8_t)(value);
}

double rover_imu_orientation_imu_cal_sys_decode(uint8_t value)
{
    return ((double)value);
}

bool rover_imu_orientation_imu_cal_sys_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t rover_imu_orientation_imu_cal_mag_encode(double value)
{
    return (uint8_t)(value);
}

double rover_imu_orientation_imu_cal_mag_decode(uint8_t value)
{
    return ((double)value);
}

bool rover_imu_orientation_imu_cal_mag_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int rover_imu_quaternion_pack(
    uint8_t *dst_p,
    const struct rover_imu_quaternion_t *src_p,
    size_t size)
{
    uint16_t imu_quat_w;
    uint16_t imu_quat_x;
    uint16_t imu_quat_y;
    uint16_t imu_quat_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    imu_quat_w = (uint16_t)src_p->imu_quat_w;
    dst_p[0] |= pack_left_shift_u16(imu_quat_w, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(imu_quat_w, 8u, 0xffu);
    imu_quat_x = (uint16_t)src_p->imu_quat_x;
    dst_p[2] |= pack_left_shift_u16(imu_quat_x, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(imu_quat_x, 8u, 0xffu);
    imu_quat_y = (uint16_t)src_p->imu_quat_y;
    dst_p[4] |= pack_left_shift_u16(imu_quat_y, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(imu_quat_y, 8u, 0xffu);
    imu_quat_z = (uint16_t)src_p->imu_quat_z;
    dst_p[6] |= pack_left_shift_u16(imu_quat_z, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(imu_quat_z, 8u, 0xffu);

    return (8);
}

int rover_imu_quaternion_unpack(
    struct rover_imu_quaternion_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t imu_quat_w;
    uint16_t imu_quat_x;
    uint16_t imu_quat_y;
    uint16_t imu_quat_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    imu_quat_w = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    imu_quat_w |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->imu_quat_w = (int16_t)imu_quat_w;
    imu_quat_x = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    imu_quat_x |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->imu_quat_x = (int16_t)imu_quat_x;
    imu_quat_y = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    imu_quat_y |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->imu_quat_y = (int16_t)imu_quat_y;
    imu_quat_z = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    imu_quat_z |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->imu_quat_z = (int16_t)imu_quat_z;

    return (0);
}

int rover_imu_quaternion_init(struct rover_imu_quaternion_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_imu_quaternion_t));

    return 0;
}

int16_t rover_imu_quaternion_imu_quat_w_encode(double value)
{
    return (int16_t)(value / 0.0001);
}

double rover_imu_quaternion_imu_quat_w_decode(int16_t value)
{
    return ((double)value * 0.0001);
}

bool rover_imu_quaternion_imu_quat_w_is_in_range(int16_t value)
{
    return ((value >= -32000) && (value <= 32000));
}

int16_t rover_imu_quaternion_imu_quat_x_encode(double value)
{
    return (int16_t)(value / 0.0001);
}

double rover_imu_quaternion_imu_quat_x_decode(int16_t value)
{
    return ((double)value * 0.0001);
}

bool rover_imu_quaternion_imu_quat_x_is_in_range(int16_t value)
{
    return ((value >= -32000) && (value <= 32000));
}

int16_t rover_imu_quaternion_imu_quat_y_encode(double value)
{
    return (int16_t)(value / 0.0001);
}

double rover_imu_quaternion_imu_quat_y_decode(int16_t value)
{
    return ((double)value * 0.0001);
}

bool rover_imu_quaternion_imu_quat_y_is_in_range(int16_t value)
{
    return ((value >= -32000) && (value <= 32000));
}

int16_t rover_imu_quaternion_imu_quat_z_encode(double value)
{
    return (int16_t)(value / 0.0001);
}

double rover_imu_quaternion_imu_quat_z_decode(int16_t value)
{
    return ((double)value * 0.0001);
}

bool rover_imu_quaternion_imu_quat_z_is_in_range(int16_t value)
{
    return ((value >= -32000) && (value <= 32000));
}
